metadata:
  name: "Check that all resources are tagged with the key - department with a known value"
  id: "CUSTOM_AWS_2"
  category: "CONVENTION"
scope:
  provider: aws
definition:
  or:
    - cond_type: "attribute"
      resource_types: "all"
      attribute: 'tags.mycompany.com.department'
      operator: "equals"
      value: tech
    - cond_type: "attribute"
      resource_types: "all"
      attribute: 'tags.mycompany.com.department'
      operator: "equals"
      value: hr
    - cond_type: "attribute"
      resource_types: "all"
      attribute: 'tags.mycompany.com.department'
      operator: "equals"
      value: accounts
    - cond_type: "attribute"
      resource_types: "all"
      attribute: 'tags.mycompany.com.department'
      operator: "equals"
      value: servicedesk
    - cond_type: "attribute"
      resource_types: "all"
      attribute: 'tags.mycompany.com.department'
      operator: "equals"
      value: sales