apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-2.1.1"

commonLabels:
  mycompany.com/policy-version: "2.1.1"

resources:
  - require-department-label/policy.yaml
  - require-known-department-label/policy.yaml
