name: Policy Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  kyverno:
    name: Kyverno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Get kyverno
        run: wget -q -O - https://github.com/kyverno/kyverno/releases/download/v1.6.2/kyverno-cli_v1.6.2_linux_x86_64.tar.gz | tar -C /usr/local/bin -xzf - kyverno

      - name: Kyverno tests
        run: kyverno test kubernetes/kyverno

  checkov:
    name: Checkov tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Get checkov
        run: pip install -r requirements.txt

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # tag=v1
        with:
          bats-version: 1.6.0

      - name: BATS tests
        run: bats infra/checkov/test.bats